# Generated by Django 5.2.1 on 2025-10-29 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compromiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_toma_compromiso', models.DateField(blank=True, null=True)),
                ('fecha_cierre_proyectada', models.DateField(blank=True, null=True)),
                ('fecha_cierre_efectiva', models.DateField(blank=True, null=True)),
                ('responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('observacion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Compromiso',
                'verbose_name_plural': 'Compromisos',
            },
        ),
        migrations.CreateModel(
            name='DotacionEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('descripcion_equipo', models.CharField(blank=True, max_length=100, null=True)),
                ('proyectado_rev2', models.IntegerField(blank=True, null=True)),
                ('total_obra', models.IntegerField(blank=True, null=True)),
                ('en_falla', models.IntegerField(blank=True, null=True)),
                ('en_mantencion', models.IntegerField(blank=True, null=True)),
                ('operadores_disponibles', models.IntegerField(blank=True, null=True)),
                ('operativos', models.IntegerField(blank=True, null=True)),
                ('reserva', models.IntegerField(blank=True, null=True)),
                ('observacion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Dotación Equipo',
                'verbose_name_plural': 'Dotaciones Equipos',
            },
        ),
        migrations.CreateModel(
            name='GrupoActividadesAnterior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoActividadesDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MonografiaCruce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cruce', models.CharField(blank=True, max_length=100, null=True)),
                ('dm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Monografía Cruce',
                'verbose_name_plural': 'Monografías Cruces',
            },
        ),
        migrations.CreateModel(
            name='MonografiaPead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tramo', models.CharField(blank=True, max_length=100, null=True)),
                ('dm_inicio', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('dm_fin', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ruta_imagen', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Monografía PEAD',
                'verbose_name_plural': 'Monografías PEAD',
            },
        ),
        migrations.CreateModel(
            name='PlanAnterior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pod', models.IntegerField(blank=True, null=True)),
                ('tipo_plan', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('id_p6', models.CharField(blank=True, max_length=50, null=True)),
                ('area_trabajo', models.CharField(blank=True, max_length=30, null=True)),
                ('descripcion_item', models.CharField(blank=True, max_length=50, null=True)),
                ('unidad', models.CharField(blank=True, max_length=10, null=True)),
                ('cantidad_programada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cantidad_real', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cumplimiento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'verbose_name': 'Plan Anterior',
                'verbose_name_plural': 'Planes Anteriores',
            },
        ),
        migrations.CreateModel(
            name='PlanDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pod', models.IntegerField(blank=True, null=True)),
                ('tipo_plan', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('id_p6', models.CharField(blank=True, max_length=50, null=True)),
                ('ruta_critica', models.CharField(blank=True, max_length=100, null=True)),
                ('area_trabajo', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion_item', models.CharField(blank=True, max_length=150, null=True)),
                ('unidad', models.CharField(blank=True, max_length=10, null=True)),
                ('cantidad_programada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cantidad_proyectada_dia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('riesgos_criticos', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Plan del Día',
                'verbose_name_plural': 'Planes del Día',
            },
        ),
        migrations.CreateModel(
            name='Pod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pod', models.IntegerField(unique=True)),
                ('fecha', models.DateField()),
                ('turno', models.CharField(blank=True, max_length=20, null=True)),
                ('inicio_periodo', models.DateField(blank=True, null=True)),
                ('fin_periodo', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'POD',
                'verbose_name_plural': 'PODs',
            },
        ),
        migrations.CreateModel(
            name='TipoGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompromisoResumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_compromiso', models.IntegerField(blank=True, null=True)),
                ('abierto', models.IntegerField(blank=True, null=True)),
                ('cerrado', models.IntegerField(blank=True, null=True)),
                ('compromiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumenes', to='pretdb.compromiso')),
            ],
            options={
                'verbose_name': 'Resumen de Compromiso',
                'verbose_name_plural': 'Resúmenes de Compromisos',
            },
        ),
        migrations.CreateModel(
            name='EquipoCompromiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_falla', models.CharField(blank=True, max_length=100, null=True)),
                ('compromiso_equipo', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_equipo', models.DateField(blank=True, null=True)),
                ('compromiso_operador', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_operador', models.DateField(blank=True, null=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compromisos', to='pretdb.dotacionequipo')),
            ],
            options={
                'verbose_name': 'Compromiso de Equipo',
                'verbose_name_plural': 'Compromisos de Equipos',
            },
        ),
        migrations.CreateModel(
            name='ActividadPead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_actividad', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('unidad', models.CharField(blank=True, max_length=10, null=True)),
                ('pead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='pretdb.monografiapead')),
            ],
        ),
        migrations.CreateModel(
            name='MonografiaPeadActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acumulado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='pretdb.actividadpead')),
            ],
            options={
                'verbose_name': 'Actividad de Monografía PEAD',
                'verbose_name_plural': 'Actividades de Monografía PEAD',
            },
        ),
        migrations.CreateModel(
            name='PlanAnteriorCnc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('causa', models.CharField(blank=True, max_length=100, null=True)),
                ('subcausa', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(blank=True, max_length=30, null=True)),
                ('descripcion_cnc', models.CharField(blank=True, max_length=200, null=True)),
                ('responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('plan_anterior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cnc', to='pretdb.plananterior')),
            ],
            options={
                'verbose_name': 'Plan Anterior CNC',
                'verbose_name_plural': 'Planes Anteriores CNC',
            },
        ),
        migrations.CreateModel(
            name='PlanAnteriorFront',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frente', models.CharField(blank=True, max_length=50, null=True)),
                ('hora_inicio_efectivo', models.TimeField(blank=True, null=True)),
                ('comentario', models.CharField(blank=True, max_length=200, null=True)),
                ('plan_anterior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fronts', to='pretdb.plananterior')),
            ],
            options={
                'verbose_name': 'Plan Anterior Front',
                'verbose_name_plural': 'Planes Anteriores Fronts',
            },
        ),
        migrations.CreateModel(
            name='PlanAnteriorGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pretdb.grupoactividadesanterior')),
                ('plan_anterior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pretdb.plananterior')),
            ],
        ),
        migrations.AddField(
            model_name='grupoactividadesanterior',
            name='planes_anteriores',
            field=models.ManyToManyField(related_name='grupos_actividades', through='pretdb.PlanAnteriorGrupo', to='pretdb.plananterior'),
        ),
        migrations.CreateModel(
            name='PlanAnteriorHoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_programada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cantidad_real', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('horas_hombre_programadas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('horas_hombre_reales', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('porcentaje_avance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('plan_anterior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horas', to='pretdb.plananterior')),
            ],
            options={
                'verbose_name': 'Plan Anterior Horas',
                'verbose_name_plural': 'Planes Anteriores Horas',
            },
        ),
        migrations.CreateModel(
            name='PlanDiaGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pretdb.grupoactividadesdia')),
                ('plan_dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pretdb.plandia')),
            ],
        ),
        migrations.AddField(
            model_name='grupoactividadesdia',
            name='planes_dia',
            field=models.ManyToManyField(related_name='grupos_actividades', through='pretdb.PlanDiaGrupo', to='pretdb.plandia'),
        ),
        migrations.CreateModel(
            name='PlanDiaRestricciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('plan_dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restricciones', to='pretdb.plandia')),
            ],
            options={
                'verbose_name': 'Restricción Plan del Día',
                'verbose_name_plural': 'Restricciones Plan del Día',
            },
        ),
        migrations.AddField(
            model_name='plandia',
            name='pod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_dia', to='pretdb.pod'),
        ),
        migrations.AddField(
            model_name='plananterior',
            name='pod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_anteriores', to='pretdb.pod'),
        ),
        migrations.AddField(
            model_name='monografiapead',
            name='pod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monografias_pead', to='pretdb.pod'),
        ),
        migrations.CreateModel(
            name='MonografiaCruceActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_actividad', models.CharField(blank=True, max_length=50, null=True)),
                ('actividad', models.CharField(blank=True, max_length=200, null=True)),
                ('unidad', models.CharField(blank=True, max_length=10, null=True)),
                ('acumulado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ruta_imagen', models.CharField(blank=True, max_length=255, null=True)),
                ('cruce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='pretdb.monografiacruce')),
                ('pod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pretdb.pod')),
            ],
            options={
                'verbose_name': 'Actividad de Monografía Cruce',
                'verbose_name_plural': 'Actividades de Monografía Cruce',
            },
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta_imagen', models.CharField(blank=True, max_length=255, null=True)),
                ('pod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layouts', to='pretdb.pod')),
            ],
            options={
                'verbose_name': 'Layout',
                'verbose_name_plural': 'Layouts',
            },
        ),
        migrations.AddField(
            model_name='dotacionequipo',
            name='pod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dotacion_equipos', to='pretdb.pod'),
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_contrato', models.CharField(blank=True, max_length=60, null=True)),
                ('nombre_codigo', models.CharField(blank=True, max_length=10, null=True)),
                ('pod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='pretdb.pod')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
        migrations.AddField(
            model_name='compromiso',
            name='pod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compromisos', to='pretdb.pod'),
        ),
        migrations.CreateModel(
            name='PpcSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('ppc_total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('programadas_total', models.IntegerField(blank=True, null=True)),
                ('realizadas_total', models.IntegerField(blank=True, null=True)),
                ('pod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ppc_semanales', to='pretdb.pod')),
            ],
            options={
                'verbose_name': 'PPC Semanal',
                'verbose_name_plural': 'PPCs Semanales',
            },
        ),
        migrations.CreateModel(
            name='PpcDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('dia_nombre', models.CharField(blank=True, max_length=10, null=True)),
                ('programadas', models.IntegerField(blank=True, null=True)),
                ('realizadas', models.IntegerField(blank=True, null=True)),
                ('ppc_dia', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ppc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ppc_diarios', to='pretdb.ppcsemanal')),
            ],
            options={
                'verbose_name': 'PPC Diario',
                'verbose_name_plural': 'PPCs Diarios',
            },
        ),
        migrations.CreateModel(
            name='RegistroCnc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestion_atribuible', models.CharField(blank=True, max_length=50, null=True)),
                ('causa_primaria_num', models.IntegerField(blank=True, null=True)),
                ('causa_primaria', models.CharField(blank=True, max_length=100, null=True)),
                ('causa_secundaria_codigo', models.CharField(blank=True, max_length=20, null=True)),
                ('causa_secundaria', models.CharField(blank=True, max_length=100, null=True)),
                ('pod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_cnc', to='pretdb.pod')),
            ],
            options={
                'verbose_name': 'Registro CNC',
                'verbose_name_plural': 'Registros CNC',
            },
        ),
        migrations.CreateModel(
            name='Sso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pod', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sso', to='pretdb.pod')),
            ],
            options={
                'verbose_name': 'SSO',
                'verbose_name_plural': 'SSOs',
            },
        ),
        migrations.CreateModel(
            name='SsoCruzSeguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('sso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cruces_seguridad', to='pretdb.sso')),
            ],
            options={
                'verbose_name': 'SSO Cruz de Seguridad',
                'verbose_name_plural': 'SSO Cruces de Seguridad',
            },
        ),
        migrations.CreateModel(
            name='SsoEstadoDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado_dia', models.IntegerField(blank=True, choices=[(0, 'Verde'), (1, 'Amarillo'), (2, 'Rojo')], null=True)),
                ('sso_cruz_seguridad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados_dia', to='pretdb.ssocruzseguridad')),
            ],
            options={
                'verbose_name': 'SSO Estado Día',
                'verbose_name_plural': 'SSO Estados Días',
            },
        ),
        migrations.CreateModel(
            name='SsoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('descripcion_dia', models.CharField(blank=True, max_length=50, null=True)),
                ('calificacion', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_compromiso', models.DateField(blank=True, null=True)),
                ('estado', models.IntegerField(blank=True, choices=[(0, 'Abierta'), (1, 'Cerrada')], null=True)),
                ('sso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='pretdb.sso')),
            ],
            options={
                'verbose_name': 'SSO Evento',
                'verbose_name_plural': 'SSO Eventos',
            },
        ),
        migrations.CreateModel(
            name='SsoReflexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hallazgos', models.IntegerField(blank=True, null=True)),
                ('tarjeta_verde', models.IntegerField(blank=True, null=True)),
                ('traslado_policlinico', models.IntegerField(blank=True, null=True)),
                ('sso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflexiones', to='pretdb.sso')),
            ],
            options={
                'verbose_name': 'SSO Reflexión',
                'verbose_name_plural': 'SSO Reflexiones',
            },
        ),
        migrations.AddField(
            model_name='grupoactividadesdia',
            name='tipo_grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pretdb.tipogrupo'),
        ),
        migrations.AddField(
            model_name='grupoactividadesanterior',
            name='tipo_grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pretdb.tipogrupo'),
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_trabajador', models.CharField(max_length=2)),
                ('nombre', models.CharField(max_length=30)),
                ('cargo', models.CharField(blank=True, max_length=20, null=True)),
                ('empresa', models.CharField(blank=True, max_length=15, null=True)),
                ('correo', models.EmailField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Trabajador',
                'verbose_name_plural': 'Trabajadores',
                'indexes': [models.Index(fields=['correo'], name='pretdb_trab_correo_f4f99d_idx')],
                'constraints': [models.UniqueConstraint(fields=('codigo_trabajador', 'empresa'), name='uq_trabajador_codigo_empresa')],
            },
        ),
        migrations.AddField(
            model_name='pod',
            name='jefe_turno_codelco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pods_como_jefe_codelco', to='pretdb.trabajador'),
        ),
        migrations.AddField(
            model_name='pod',
            name='jefe_turno_contratista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pods_como_jefe_contratista', to='pretdb.trabajador'),
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='pretdb.pod')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='pretdb.trabajador')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
            },
        ),
        migrations.CreateModel(
            name='AsistenciaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('dia_nombre', models.CharField(blank=True, max_length=8, null=True)),
                ('presente', models.IntegerField(blank=True, choices=[(0, 'Ausente'), (1, 'Presente'), (2, 'Reemplazo')], null=True)),
                ('asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pretdb.asistencia')),
            ],
            options={
                'verbose_name': 'Detalle de Asistencia',
                'verbose_name_plural': 'Detalles de Asistencia',
                'indexes': [models.Index(fields=['fecha'], name='pretdb_asis_fecha_cd21ca_idx')],
                'constraints': [models.UniqueConstraint(fields=('asistencia', 'fecha'), name='uq_asistencia_detalle')],
            },
        ),
        migrations.AddConstraint(
            model_name='plananteriorgrupo',
            constraint=models.UniqueConstraint(fields=('plan_anterior', 'grupo'), name='uq_plan_anterior_grupo'),
        ),
        migrations.AddConstraint(
            model_name='plandiagrupo',
            constraint=models.UniqueConstraint(fields=('plan_dia', 'grupo'), name='uq_plan_dia_grupo'),
        ),
        migrations.AddIndex(
            model_name='plandia',
            index=models.Index(fields=['fecha'], name='pretdb_plan_fecha_d02294_idx'),
        ),
        migrations.AddIndex(
            model_name='plananterior',
            index=models.Index(fields=['fecha'], name='pretdb_plan_fecha_cd956e_idx'),
        ),
        migrations.AddConstraint(
            model_name='dotacionequipo',
            constraint=models.UniqueConstraint(fields=('pod', 'descripcion_equipo'), name='uq_dotacion_equipo'),
        ),
        migrations.AddConstraint(
            model_name='contrato',
            constraint=models.UniqueConstraint(fields=('pod', 'nombre_contrato', 'nombre_codigo'), name='uq_contrato_por_pod'),
        ),
        migrations.AddIndex(
            model_name='compromiso',
            index=models.Index(fields=['fecha_toma_compromiso', 'fecha_cierre_efectiva'], name='pretdb_comp_fecha_t_2581e2_idx'),
        ),
        migrations.AddIndex(
            model_name='ppcsemanal',
            index=models.Index(fields=['fecha_inicio', 'fecha_fin'], name='pretdb_ppcs_fecha_i_2b53e9_idx'),
        ),
        migrations.AddConstraint(
            model_name='ppcdiario',
            constraint=models.UniqueConstraint(fields=('ppc', 'fecha'), name='uq_ppc_diario'),
        ),
        migrations.AddConstraint(
            model_name='ssoestadodia',
            constraint=models.UniqueConstraint(fields=('sso_cruz_seguridad', 'fecha'), name='uq_sso_estado_por_dia'),
        ),
        migrations.AddIndex(
            model_name='ssoevento',
            index=models.Index(fields=['fecha'], name='pretdb_ssoe_fecha_aac9be_idx'),
        ),
        migrations.AddIndex(
            model_name='pod',
            index=models.Index(fields=['fecha'], name='pretdb_pod_fecha_6d1d87_idx'),
        ),
        migrations.AddConstraint(
            model_name='asistencia',
            constraint=models.UniqueConstraint(fields=('pod', 'trabajador'), name='uq_asistencia_pod_trab'),
        ),
    ]
