# Generated by Django 5.2.7 on 2025-11-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plananterior',
            name='realizada',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
