# Generated by Django 5.2.7 on 2025-11-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretdb', '0002_plananterior_realizada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistenciadetalle',
            name='dia_nombre',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='nombre_codigo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='nombre_contrato',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='monografiacruce',
            name='dm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='monografiapead',
            name='dm_fin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='monografiapead',
            name='dm_inicio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='codigo_trabajador',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='empresa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
