# Generated by Django 5.2.7 on 2025-11-17 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pretdb', '0004_alter_compromiso_descripcion_and_observacion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistroCnc',
            new_name='MatrizCNC',
        ),
    ]
