# Generated by Django 5.2.7 on 2025-11-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretdb', '0005_rename_registrocnc_matrizcnc'),
    ]

    operations = [
        migrations.AddField(
            model_name='plandia',
            name='tipo_actividad',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
