# Generated by Django 5.2.7 on 2025-11-18 15:12

import django.db.models.deletion
from django.db import migrations, models


def _migrate_contratos(apps, schema_editor):
    Contrato = apps.get_model('pretdb', 'Contrato')
    Pod = apps.get_model('pretdb', 'Pod')

    key_map = {}
    for contrato in Contrato.objects.all().order_by('id'):
        key = (
            (contrato.nombre_codigo or "").strip(),
            (contrato.nombre_contrato or "").strip(),
        )
        if not any(key):
            if contrato.pod_id:
                Pod.objects.filter(id=contrato.pod_id).update(contrato=None)
            contrato.delete()
            continue
        canonical = key_map.get(key)
        if canonical is None:
            canonical = contrato
            key_map[key] = canonical
        if contrato.pod_id:
            Pod.objects.filter(id=contrato.pod_id).update(contrato=canonical)
        if canonical.id != contrato.id:
            contrato.delete()


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('pretdb', '0006_plandia_tipo_actividad'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contrato',
            name='uq_contrato_por_pod',
        ),
        migrations.AddField(
            model_name='pod',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pods', to='pretdb.contrato'),
        ),
        migrations.RunPython(_migrate_contratos, _noop),
        migrations.RemoveField(
            model_name='contrato',
            name='pod',
        ),
        migrations.AddConstraint(
            model_name='contrato',
            constraint=models.UniqueConstraint(fields=('nombre_codigo', 'nombre_contrato'), name='uq_contrato_codigo_nombre'),
        ),
    ]
